task: detection

num_classes: 10
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /kaggle/input/dataset-rt-detr2/train/images
    ann_file: /kaggle/input/dataset-rt-detr2/train/images/annotations.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 16
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /kaggle/input/dataset-rt-detr2/valid/images
    ann_file: /kaggle/input/dataset-rt-detr2/valid/images/annotations.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 16
  num_workers: 4
  drop_last: False
